### PR TITLE
Simplify timeout-dialog so polyfills can be removed, reducing overall bundle size

### PR DESCRIPTION
**Pull request by gunjam**
The total js bundle size for our service is 40kb, removing the polyfills in `timeout-dialog.js` reduces our bundle to 30kb, meaning 25% of the js we were shipping was just polyfills for the timeout-dialog component. So I've simplifed the code to remove functions (such as `Object.assign()`) that require polyfilling.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by matthewmascord** [comment]
@gunjam does our providing the source JS in the NPM package allow you to do what you want now?

**Pull request closed without merging**
